# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80397d56a275d291304d9afc3564cbaaad38ad76fdbdae82a95400296e82a147941001700ccd858aced85f9fb08d9e931e400c61bbc1d44c5e0e49fdb304d902

test:
  secret_key_base: 520762bd7757bce3891c9a58cf890a88e95f89257a6eb4be8ea6ac87a3cbc8e8f4269563b54c35fc518da37e31dc397f29f3f3789c1e1615f9726306775dd01d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
